/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Contact: typeof import('./src/components/Contact.vue')['default']
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    Intro: typeof import('./src/components/Intro.vue')['default']
    PoemAudio: typeof import('./src/components/PoemAudio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Solutions: typeof import('./src/components/Solutions.vue')['default']
    ThoughtBubble: typeof import('./src/components/ThoughtBubble.vue')['default']
    Work: typeof import('./src/components/Work.vue')['default']
  }
}
